### ISSUE TITLE
Next.js support?

### ISSUE THREAD

**Issue by MicroBenz** [guess-js/guess#46]
Does this library will be support for Next.js?

**Comment by addyosmani** [comment]
We currently supporting parsing routes for applications scaffolded using create-react-app, some React boilerplates and Gatsby but don't at this time explicitly support Next. 

I see from https://github.com/zeit/next.js/issues/1632 that Next uses it's own router rather than React Router so we would probably need to write custom support for their router in our parser package.

@mgechev and I have talked about this being one of the next logical frameworks to support.
